services:
  service2_1:
    build:
      context: ./src/service2_1
    container_name: service2_1
    ports:
      - "5301:5301"
    networks:
      - pasidnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5301/health"]
      interval: 20s
      timeout: 2s
      retries: 15

  service2_2:
    build:
      context: ./src/service2_2
    container_name: service2_2
    ports:
      - "5302:5302"
    networks:
      - pasidnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5302/health"]
      interval: 20s
      timeout: 2s
      retries: 15

  lb1:
    build:
      context: ./src/load_balancer1
    container_name: lb1
    ports:
      - "5101:5101"
    networks:
      - pasidnet
    depends_on:
      service2_1:
        condition: service_healthy
      service2_2:
        condition: service_healthy

  lb2:
    build:
      context: ./src/load_balancer2
    container_name: lb2
    ports:
      - "5201:5201"
    networks:
      - pasidnet
    depends_on:
      service2_1:
        condition: service_healthy
      service2_2:
        condition: service_healthy

  source:
    build:
      context: ./src/source
    container_name: source
    depends_on:
      - lb1
    ports:
      - "5000:5000"
    networks:
      - pasidnet

networks:
  pasidnet:
    driver: bridge
